LmeSzinc/AzurLaneAutoScript

config/template.ini, module/config/argparser_en.py, module/config/config.py, module/exercise/exercise.py, module/exercise/opponent.py
Revamped exercise to use date, configurations, and opponent_change_count.  Added several helper methods to save data as needed and allow re-runs of exercise if needed. Added new mode 'easiest_else_exp' and exclusive method for mode as this performs exactly two rounds of pvp then moves onto to the next change in 4 opponents. Just as it describes, if unable to beat easiest opponent then switch to max exp opponent and accept the loss. Both _exercise_once and _excercise_easiest_else_exp have been tested and seem to be behaving correctly under the revamped exercise implementation.
=> Exercise Module Updates

module/research/project.py
Previous research detail page may not disappear immediately after pressing the DETAIL_NEXT button. Waiting until touch effect to fade should prevent this from breaking the script.
=> Fix: [JP] Research not working properly in some cases.

module/logger.py
The default character encoding of "logging" is cp1252, which is not able to encode CJK chars.
Commission names in JP server (maybe also CN server) could cause logging errors like this:
`2020-09-15 19:55:53.839 | INFO | 上級資材整理 (Genre: major_comm, Status: pending, Duration: 10:00:00)`
`--- Logging error ---`
`Traceback (most recent call last):`
`  File "D:\Program\AzurLaneAutoScript\toolkit\lib\logging\__init__.py", line 1028, in emit`
`    stream.write(msg + self.terminator)`
`  File "D:\Program\AzurLaneAutoScript\toolkit\lib\encodings\cp1252.py", line 19, in encode`
`    return codecs.charmap_encode(input,self.errors,encoding_table)[0]`
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>`
`Call stack:`
`  File "alas_jp.pyw", line …
=> Fix: Log charset set to UTF-8

alas.py
82277e3d5a9878a2204b178bb24ccfa94a839974 changed log char encoding to UTF-8 and it broke 'save_error_log'.
=> Fix: Error log char encoding set to UTF-8

module/research/research.py, module/reward/reward.py, module/reward/tactical_class.py
To ensure that nothing is pending before exiting page_reward. It also avoids using research_receive() function in RewardResearch class which might be unstable because of too many sleep().
=> Opt: reward receiving logic optimization

module/combat/hp_balancer.py
The logic of hp balancer for 3 ships now is that, to reposition two adjacent units in 'descending' if and only if their difference is greater than threshold / 2.
=> Opt: minor optimization in hp balancer

module/reward/dorm.py
FOOD buttons should not contain the corners because only the inside areas are clickable.
=> Fix: FOOD ButtonGrid area fix

module/sos/sos.py
relevant for fleet_2 = 0
Alternatively, can consider re-work the `fleet_boss` method itself but due to relation with other modules, difficult to determine overall impact may cause. Chose config backup method for quick easy resolution.
```
@property
def fleet_boss(self):
if self.config.FLEET_BOSS == 2 or self.config.FLEET_2:
return self.fleet_2
else:
return self.fleet_1
```
=> Fix: sos clear potential boss stuck due to default FLEET_BOSS=2

module/equipment/equipment.py
Disabling ensure_template repairs this behavior and retains
if new ship is actually detected
Used a custom script debugger to run through simulated scenarios in this case when enhancing and swiping
[module_check.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5745031/module_check.zip)
Removing that flag setting in equipment.py, will result in the problematic scenario in which the first swipe, if there are no adjacent ships, then it will think its a new ship anyway and the second swipe will properly detect.  Apparently on the first swipe, it is 0% similarity according to match(), not entirely sure why but just an observation.
=> Fix: On first round, often same ship is detected as new ship

campaign/event_20200917_cn/campaign_base.py, campaign/event_20201029_cn/campaign_base.py, campaign/event_20201126_cn/campaign_base.py, module/campaign/campaign_ocr.py, module/guild/operations.py
This was added in the case ocr resulted in an unexpected stage name that did not belong in any list.  Applied same principal to other counterparts should a rerun happen in the near future.
Fix: Invalid place for 'and' operator, the else clause should not have executed in case the combat was successful, lack of testing on my part.
=> Fix: Additional raise clause for method

module/config/argparser_en.py, module/config/argparser_jp.py
Opt: [EN, JP] Update message as leaving blank did not do as intended, must insert at least one white space character to configure as `no index filter` otherwise still uses old populated value
TODO: [CN, TW] may want to update their help message as well if desired
=> Opt: [EN, JP] Update help message enhance_order_string

module/os/map_operation.py
- get_map_shape for Méditerranée name maps, NY City ocr'ed as NV City
=> Fix: [EN] Add extra conditionals for certain maps

module/map/camera.py
It was a quite rare case.
The emulator sometimes treat a swipe as a click (mostly on potato pcs). If this happens while doing map_swipe(), the fleet might step on a mystery, then GET_ITEMS_1 would raise MapDetectionError.
Here is the error log:
```
2021-02-11 07:56:12.213 | INFO | Map swipe: (0, 1)
2021-02-11 07:56:12.213 | INFO | Swipe ( 719,  484) -> ( 717,  344), 0.167
2021-02-11 07:56:13.053 | INFO |            tile_center: 0.615 (bad match)
2021-02-11 07:56:13.251 | INFO |            tile_corner: 0.750 (bad match)
2021-02-11 07:56:13.350 | INFO |         tile_rectangle: 0 rectangles (bad match)
2021-02-11 07:56:13.353 | WARNING | Image to detect is not in_map
2021-02-11 07:56:13.354 | ERROR | Failed to find a free tile
Traceback (most recent call last):
File …
```
=> Fix: GET_ITEMS_1 raises MapDetectionError

module/map/map_fleet_preparation.py
Cropping FLEET_*_IN_USE can avoid wasting time on handling the info_bar. 5113cf9d554872c891b8a0931afd2000067f3e6d
To avoid double-clicking on the clear button, sleep() is needed. (No side effect now.)
=> Opt: Avoid double-clicking CLEAR

module/combat/auto_search_combat.py
As title states, after combat for auto-search new ships are displayed after battle, already obtained ships even for elite are not displayed seem to be the exception.
=> Fix: New ship drop can result in game stuck exception during auto-search

module/guild/logistics.py, module/os/fleet.py
- guild_logistics too many clicks due to poor timing screen capture is actually pretty frequent for my pc so kept as personal change unless another reported something similar. In use for weeks personally, no issue as far as I can tell.
- Recent change in camera.py considers mystery encounter on path, os_clear_map can run into something similar with unexpected object on path as well. So optimized to handle those situations.
=> Fix: guild_logistics and handle_mystery for os_clear_map

module/map/map_operation.py
If SWITCH_OVER not appeared (in most cases, connection unstable), we should wait for it instead of skipping the switch click.
Here the fleets were messed up.
```
2021-02-21 12:22:30.111 | INFO | Using function: battle_0
2021-02-21 12:22:30.111 | INFO | Fleet 2 step on
2021-02-21 12:22:30.115 | INFO | Fleet_2 step on A3
2021-02-21 12:22:30.115 | INFO | Switch over
2021-02-21 12:22:30.116 | WARNING | No buttons detected.
2021-02-21 12:22:31.153 | INFO |            tile_center: 0.955 (good match)
2021-02-21 12:22:31.169 | INFO | 0.081s  _   edge_lines: 3 hori, 2 vert
2021-02-21 12:22:31.169 | INFO | Edges: /_\   homo_loca: ( 25,  56)
2021-02-21 12:22:31.173 | INFO |            center_loca: (3, 2)
2021-02-21 12:22:31.173 | INFO |                 Camera: H1
```
=> Fix: fleet_switch_click() may fail when SWITCH_OVER not appeared

module/map_detection/grid_info.py
We use 'is_sea' to find path in find_path_initial(). Sirens cannot be passed through, so they should not be tagged 'is_sea'.
For example:
```
2021-03-28 04:33:08.729 | INFO |    A  B  C  D  E  F  G  H
2021-03-28 04:33:08.729 | INFO |  1 -- -- -- -- ++ ++ -- --
2021-03-28 04:33:08.729 | INFO |  2 -- 2M -- AR ++ ++ FL --
2021-03-28 04:33:08.729 | INFO |  3 ++ ++ ++ -- -- -- -- Fl
2021-03-28 04:33:08.729 | INFO |  4 -- -- -- -- -- -- -- --
2021-03-28 04:33:08.730 | INFO |  5 ++ ++ ++ -- ++ -- -- --
2021-03-28 04:33:08.730 | INFO |  6 -- -- -- -- 2C -- ++ --
2021-03-28 04:33:08.730 | INFO |  7 -- -- -- -- -- SA -- --
2021-03-28 04:33:08.734 | INFO |      A    B    C    D    E    F    G    H
2021-03-28 04:33:08.735 | INFO |  1    9    8    7    6 9999 9999    1    2
2021-03-28 04:33:08.735 | …
```
=> Fix: sirens are not sea and cannot be passed through

module/os_combat/combat.py
Map event may appear too quickly before detection of exit thereby becoming stuck
For safety, keeping handle_map_event at its original timing place still may be needed so opted in not just relocating when it happens.
Pastebin log: https://pastebin.com/1FvZH5x2
=> Fix: Handle potential map_event stuck

module/os_handler/action_point.py
在重置前最后一天使用行动力箱子使得行动力超过200时会出现以下提示，需要识别处理。
=> Fix: handle popup of action_point_use

module/config/dictionary.py
启动大世界每月全清后报以下错误
```
Traceback (most recent call last):
File "E:\games\AzurLaneScript\AzurLaneAutoScript\alas_jp_cn.pyw", line 8, in <module>
main()
File "E:\games\AzurLaneScript\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 130, in <lambda>
return lambda *args, **kwargs: func(*args, **kwargs)
File "E:\games\AzurLaneScript\AzurLaneAutoScript\module\config\argparser.py", line 551, in main
config[command][key] = str(value)
File "E:\games\AzurLaneScript\AzurLaneAutoScript\toolkit\lib\configparser.py", line 958, in __getitem__
raise KeyError(key)
KeyError: 'Os_clear_world'
```
在全部文件里只有`dictionary.py`能找这个词
里面出现`'os_clear_world': 'os_clear_world'`和`'大世界每月全清': 'os_clear_world'`
看了下ini文件里用的是`Os_world_clear`，怀疑是`dictionary.py`里的值写错了 …
=> Fix: correct items in dictionary.py

module/os_handler/action_point.py, module/statistics/item.py
This screenshot was recognized as [358, 62, 0, 0].
Tuning the threshold from 64 to 96 solved the problem.
Here are the pre-processed images with thresholds 64, 96 and 128. I think 96 is a good balance.
=> Fix: item number OCR wrong

module/combat/hp_balancer.py, module/config/argparser_en.py, module/os/fleet.py
- Deprecate `@Config` use for `_hp_grid` to allow differentiated use depending on running module.  Otherwise, only the last defined is used.
- Spell check in argparser_en
=> Fix: [EN] HP check in normal vs os

module/device/connection.py
This PR should achieve compatibilty with Linux systems by using ADB provided by the distribution package manager.
For some reason
`process = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)`
causes problems, so a check for Linux adb binary is implemented to change `shell=False`
=> Linux compatibility

module/handler/fast_forward.py, module/os/operation_siren.py
- Removing the offset allows consistent detection of box on different maps. For some reason, campaigns with blue vs red (chapter vs event) background contributes to the color of the box so offset works exclusively for one but not the other. Though it seems box detection when in fleet preparation has no issue with offset being specified regardless of map.
- I wouldn't say the hp_reset move is a fix but it was something I had forgotten to do in the initial PR since it should reset after either case whether their fleet went to port or not.
Didn't want to commit this since it is a hack but I do often get `PINNED_DISABLE` too many tries exception. But maybe something to consider since a degree of randomness does factor in encountering this and I don't think disturbs too much as the too long …
=> Fix: 2x book detect in auto search continue/exit

module/os/map_operation.py
in the name of "St. Petersburg".
This should fix #464.
=> Fix: [JP] Katakana "pe" may be OCRed as Hiragana

module/handler/fast_forward.py
Can throw off timing and re-enter `handle_2x_book_setting` due to immediate detection of residual button displayed after click as its current `interval=2` lapse can long pass within `handle_2x_book_setting`.
=> Fix: interval_reset for AUTO_SEARCH_MENU_CONTINUE

module/raid/daily.py, module/raid/raid.py, module/raid/run.py
#532 #522 
共斗和每日共斗使用同一个设置项可能会使config维护较为麻烦
因此修改raid相关代码使其能够正确读取使用 raid_daily_name
=> Fix: use raid_daily_name (not raid_name) in Daily

module/device/connection.py
adb connect连的是ip+端口，应该连不上emulator-55xx吧（
这里我猜测用途是用于连接端口不在5555-5585之间的模拟器，也就是说是ip+端口形式，所以稍微改了下判断，让脚本检测到serial中包含"emulator"的时候跳过这个步骤（
第一次提pr，有啥问题请见谅（
~~主要是每次开脚本都硬拖我10几秒很不开心，就去看了2分钟python教程改掉了~~
=> 跳过尝试连接emulator

alas.py, config/template.json, module/config/argument/args.json, module/config/argument/menu.json, module/config/argument/override.yaml, module/config/argument/task.yaml, module/config/config_manual.py, module/config/i18n/en-US.json, module/config/i18n/ja-JP.json, module/config/i18n/zh-CN.json, module/config/i18n/zh-TW.json, module/shop/shop_reward.py
Due to general shop changing inventory 3 times daily, other shops 1 time daily
Simplify the date validating into splitting as 2 tasks differentiated by their `server update`
Primarily helps consistent task runs when not using Alas 24/7
=> Fix: Split shop task

config/template.json, module/config/argument/args.json, module/config/argument/argument.yaml, module/config/config_generated.py, module/config/i18n/en-US.json, module/config/i18n/ja-JP.json, module/config/i18n/zh-CN.json, module/config/i18n/zh-TW.json, module/reward/reward.py
有个bug
如果领取任务奖励不勾选的话，领取周任务奖励，勾选也没用
不过这种场景不多吧
还是我要在help里说明一下？
还有，我把配置读取 `Reward_CollectWeeklyMission`写到了`reward_mission()`方法里面，是不是不太好，我看你配置是在`run()`里面读取判断的
```
if self.config.Reward_CollectMission:
self.ui_goto(page_main)
self.reward_mission()
```
但是那样的话我就要传参给`reward_mission()`，感觉改动多不太好
=> ADD: CollectWeeklyMission

module/war_archives/war_archives.py
不知道那个`self.ui_go_to_main()` 有必要留着吗？
我看你特地备注的，估计有用吧，没动他
=> Fix: Correct WarArchives's task delay logic

module/device/method/utils.py
When a device that has been connected wirelessly is disconnected passively, it does not disappear from the adb device list,
but will be displayed as offline.  
In many cases, such as disconnection and recovery caused by network fluctuations, or after VMOS reboot when running Alas on a phone, the device is still available, but it needs to be disconnected and re-connected.
=> Fix: reconnect when device offline

module/device/method/ascreencap.py, module/device/method/hermit.py, module/device/method/minitouch.py, module/device/method/uiautomator_2.py, module/device/method/wsa.py
It's weird to see a `retry_wrapper` while running benchmark  
before:  
after:  
我是废物,我连分支切换都搞不定
=> Fix: add [at]wraps to retry_wrapper to display actual function name in benchmark log output

module/device/method/utils.py
`ascreencap.py` line 166 `Ascreencap.screenshot_ascreencap` passed `stream=True` param to `adb_shell` which finally called `AdbClient.shell` in `adbutils`  
But timeout is only set when `stream is False` (`adbutils/__init__.py` line 335 `AdbClient.shell`), so actually the next step `recv_all` will run without timeout protection  
When `recv_all` takes a `Socket` (only in `Connection.adb_shell_nc`), it has already set a timeout before calling  
So the `settimeout` statement is added under the case of taking an `_AdbStreamConnection` object, which affects on ADB and aScreencap screenshot methods
=> Fix: Add timeout to ADB and aScreencap screenshot

module/commission/commission.py
alas在滑动异常导致的一轮委托识别失效后不会重置委托界面状态，
导致第二轮委托识别只会识别最下几个委托，
如果目标委托在靠上的位置则永远识别不到，
这个pr补充了在一轮识别失败后重置界面的部分
=> Fix: An accidental exception causes the commission to fail

module/daemon/uncensored.py
When I try to use Uncensored Patch in Linux, alas reports an error saying `no module named winreg`.  
emmm, Linux definitely doesn't have winreg, and I found out that Uncensored Patch doesn't even need winreg.
winreg is indirectly imported by `deploy.installer` when importing `GitManager`, which can be directly imported by `deploy.git`, just like other code in alas.
=> Fix: Non-Windows OS Uncensored Patch error

module/config/argument/args.json, module/config/argument/argument.yaml, module/config/config_generated.py, module/config/i18n/en-US.json, module/config/i18n/ja-JP.json, module/config/i18n/zh-CN.json, module/config/i18n/zh-TW.json, module/research/project.py, module/research/research.py
因为缺少样本，这个pr只经过了最初步的测试
如果能做的项目只有reset，shortest或cheapest，则放宽限制重新检查
这并不是完全意义上的“无项目可做”，但是考虑到alas代码之间传参的难度，这是一个非常高效的近似解
如果reset在第一位但是后面还有其他项目则不会触发重新检查，不会带来不必要的收益亏损
New settings have been added so that research will hardly stop because there are no projects to choose from.
=> Add: new setting makes research more stable

module/device/connection.py
This PR attempts to fix #1236 
- Add check for AVD and return loopback IP 10.0.2.2
- Force `host = '127.0.0.1'` for docker setup
- So far `host = socket.gethostbyname(socket.gethostname())` when used on host + local emulator will return `127.0.0.1` regardless
- With some linux setup, there is `127.0.1.1 hostname` entry in `/etc/hosts` (for loopback to localhost) which will error out `nc` as above command will return `127.0.1.1`
- Hardcoding `127.0.0.1` for any emulator setup is sensible
=> Fix nc server loopback IP for AVD (fix #1236)

module/config/config.py
我就不信这也能翻车
现在时间格式错误的任务会显示在“队列中”的最上方，
并且在启动调度器的时候报错，
再也不用手动改配置文件了
PS：因为现在报错系统还没做好，就这样将就一下好了，我觉得够用了
=> Fix: Alas webui shutdown caused by datetime error

module/research/research.py
旧的逻辑直接照搬过来会在非常罕见的情况下（指空过科研但是在空过的时候有科研好了）下出问题
直接换了一个更加准确的方案
=> Fix: Delay research incorrectly when project nearly complete

module/campaign/gems_farming.py
目前做了3个部分的优化
1. 调整原有的旗舰等级选择，从1替换到区间[1, 31]以复用被更换下来的旗舰
2. 增加了心情阈值，避免仅出击1战就撤退的情况，提高门票的利用率
3. 当前后排任一个无法更换时，推迟任务，避免无意义的频繁操作
=> Opt: Reuse flagship; Add emotion threshold; Delay if not change

module/device/connection.py, module/device/emulator.py
把重试迁到了外面，这样启动模拟器的时候如果失败或者卡死，就会关闭模拟器然后再次启动而不是直接结束
小改了一下提示，让启动模拟器的时候不会一堆critical
=> Fix: Restart the emulator after startup timeout

deploy/docker/Dockerfile.cn, docker-compose.yml
Prepare `Dockerfile` for `podman` deployment instead of `docker`
Close #1569, will break docker and docker compose deployment
Co-authored-by: jellllly420 <64725601+jellllly420@users.noreply.github.com>
=> feat: Dockerfile for Podman

submodule/AlasMaaBridge/module/config/i18n/zh-CN.json, submodule/AlasMaaBridge/module/handler/handler.py
两个commit分别针对MAA插件的以下问题：
- 检查serial，如果是蓝叠hyper-v版则自行检测adb端口，这部分代码基本上是从`module/device/connection_attr.py`里复制粘贴的；
- 修改自定义基建部分对时段的处理，如果是跨天的情形则将其下次执行时间延缓到第二天相应时段。
=> 优化了MAA插件的serial检测和自定义基建

module/retire/scanner.py
`super().scan(image, cached, output)` is None if cached=True, which cause error
=> Fix: Return None if results cached

config/deploy.template-AidLux-cn.yaml, config/deploy.template-AidLux.yaml, config/deploy.template-cn.yaml, config/deploy.template-docker-cn.yaml, config/deploy.template-docker.yaml, config/deploy.template.yaml, deploy/config.py, deploy/git.py, deploy/pip.py, deploy/template
增加了一个SSLVerify的选项，
使得在不安全网络环境下的用户（比如校园网或者野鸡代理），
可以通过牺牲自己本来就不存在的安全性，
绕过SSL证书更新Alas
由于会对其他用户的网络安全造成影响所以做成了选项
PS：这个可能需要打包成release
=> Add: Option to skip SSL verify

deploy/adb.py, module/device/connection.py
尝试修复了部分情况下在安装u2的时候会出现ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))的问题
问题的原因是连接内置的GitHub镜像失败，然后尝试裸连GitHub也失败，Error的内容跟错误的根本原因关系不大
解决方法是把内置的GitHub镜像退化成http然后再试一次，兼顾了重试和绕过安全连接
=> Fix: Error 10054 when install uiautomator2

module/os/map.py
因为异步点击的bug会导致战斗结束的时候进入大世界地图
所以修改了点击goto_main的条件
=> Fix: Handle in_globe in interrupt_auto_search caused by bug

submodule/AlasMaaBridge/module/handler/asst_backup.py, submodule/AlasMaaBridge/module/handler/handler.py
尝试修复了#1937 （高版本的Windows无法正常调用MAA）
提前加载onnxruntime.dll以避免python从错误的位置加载
本地测试没有问题
=> Fix: OSError when loading MAA

module/campaign/os_run.py, module/config/config.py, module/os/operation_siren.py
=> Fix: Wrong log when delay across task

module/os/operation_siren.py, module/os_handler/action_point.py
将短猫的溢出行动力检查改成只在侵蚀1未启用的时候运行
侵蚀1启用的时候这部分行动力会由侵蚀1消耗掉
=> Fix: Overconsumption of AP by meowfficer farming

module/config/config_manual.py, module/os/map.py, module/os/operation_siren.py
允许启用侵蚀1功能但黄币不足的时候运行其他大世界任务，
避免黄币不足和侵蚀1失败的情况下坐标堆积的问题
=> Fix: Keep 1000 AP only when CL1 available but not enabled

module/webui/process_manager.py
修复了在自动启动调度器时错误的把mod配置文件识别为alas启动的问题
=> Fix: Wrongly identify mod when auto-run config

deploy/docker/Docker-run.sh, deploy/docker/Dockerfile, deploy/docker/Dockerfile.cn, docker-compose.yml
Try to add MAA support when building alas docker image
Users should download and extract MAA latest release archive to a specific path(`../MAA`), and then uncomment `# - '../MAA:/app/MAA'` in `docker-compose.yml`, and now they can build a new alas image with MAA support.
In addition, they need to change the `MaaEmulator.MaaPath.name` to `/app/MAA` in MAA configuration.
Tip. Since the MAA latest release is built by g++12 and requires GLIBC 2.32 or higher, we changed the base docker image to ubuntu jammy(22.04 LTS), which already have prebuilt GLIBC 2.35
=> Opt: Add optional MAA installation for Docker

module/os/operation_siren.py
Same issue as with OpsiArchive, because both don't require AP to run
=> Fix: OpsiMonthBoss is running before OpsiExplore finishes

deploy/docker/Dockerfile, deploy/docker/Dockerfile.cn
This is the Dockerfile I have used in Docker Desktop with Hyper-V backend, Win 10.  
See [https://github.com/hgjazhgj/Alas_Docker_BlueStacks5](https://github.com/hgjazhgj/Alas_Docker_BlueStacks5).  
The image size is reduced from 2.44GB to 1GB.  
I am not sure how to do for Dockerfile.cn, it seems that the origin Dockerfile will download some files from GitHub..., and apt sources are not changed.  
I also have Dockerfile for AArch64, running in my RaspberryPi, but using 3rd party MXNet from [https://www.binss.me/blog/run-azurlaneautoscript-on-arm64/](https://www.binss.me/blog/run-azurlaneautoscript-on-arm64/), dose it have the chance to merge into Alas?
=> Opt: Extremely reduce image size built by Dockerfile (-59%)

deploy/git.py
Fix the problem of getting stuck when entering the interactive interface when the pager prints the update log.
在 Linux 环境下手动安装，在挂机自动更新时，如果 git 配置了 pager，git log --no-merges -1 命令会进入交互界面，需要按 q 退出，导致程序不能自动化，这个补丁通过 --no-pager 参数修复了这个问题
=> Fix: Fix update stuck issue

module/device/method/adb.py
修复在没有物理按键的设备，比如 X8 沙箱中，无法启动游戏的问题。
由于没有物理按键，monkey 指令会报告： SYS_KEYS has no physical keys but with factor 2.0%
使用 --pct-syskeys 0 参数解决了这一问题，由于本程序使用 monkey 的目的只是启动游戏，增加该参数对其他有物理按键的设备也不会有影响。
在代码中还发现使用  am start 的后备方案对于 android 5.1 的设备也存在问题（并没有在这个 PR 中修复）
代码逻辑中使用正则匹配主 activity 名称，但是 dumpsys 的输出不同版本可能不同，比如安卓 5.1 的输出，无法使用该表达式匹配。
我比对了游戏从 2017 年至今的包，其 main activity 名称没有变化，建议可以固定为：com.manjuu.azurlane.MainActivity，当然可能需要根据区服进行适配。
Fix the problem that the game cannot be launched on devices without physical buttons, such as the X8 sandbox.
Since there are no physical keys, the monkey command will report: SYS_KEYS has no physical keys but with factor 2.0%
Use --pct-syskeys 0 parameter to solve this problem, since the purpose of using monkey in this program is only to start the game, adding and changing …
=> Fix lanuch game in no physical keys device

submodule/AlasMaaBridge/module/handler/handler.py
=> Fix: Wrong condition in MAA infrast

module/campaign/run.py
Now when remaining number of times of hard mode is 0, the task will be delayed to next day
=> Fix: Skip main task of hard mode when remaining number of times is 0

module/os/map.py
开启侵蚀1后，在短猫侵蚀5碰到探测塔时直接不踩了，这有可能影响海域成就星刷取。
=> Fix: scanning tower skip should only operate in cl1 zones.

module/os/operation_siren.py
修复了短猫的行动力限制月初会被重置的问题
顺便修改了一下侵蚀1的预填行动力，由于行动力箱子的固定存量导致侵蚀1预填的行动力实际上会超出设定值，因此略微降低设定值以平衡这个问题
=> Fix: ActionPointPreserve reset by error

module/daily/daily.py
破交作战改成4次之后，OCR似乎无法正确识别。
修改了一下识别button的大小，破交作战的数字“4”应该可以正确识别了，但是不知道会不会影响其他数字的识别？
=> Fix OCR for supply line disruption

module/gacha/gacha_reward.py
建造完成时会出现空队列背景干扰循环，该pr加入了状态锁定以免误触空队列条件 #2834
=> Fix: Error caused by queue clean status flashback

module/tactical/tactical_class.py
当只有一个技能的舰娘技能满级时，会出现无法识别的情况，导致Alas一直重复尝试点击一个不存在的技能按钮，最终导致异常停止。
1. 确保在战术学院中能选择到的第一只舰娘只有一个技能，且该技能处于满级状态。例如：
2. 启动Alas，手动触发技能学习，保证此时战术学院仍有空位。
3. 等待错误出现。
```text
2023-10-18 21:51:26.040 | INFO | [DOCK_SELECTED 0.013s] 0/1                                                            
2023-10-18 21:51:26.043 | INFO | Click ( 183,  149) @ CARD_0_0                                                         
2023-10-18 21:51:26.265 | INFO | [DOCK_SELECTED 0.008s] 1/1                                                            
2023-10-18 21:51:26.282 | INFO | Click (1004,  669) @ SHIP_CONFIRM                                                     
2023-10-18 21:51:26.863 | INFO | <<< TACTICAL SKILL CHOOSE >>>                                                         
2023-10-18 21:51:26.878 | INFO | Loading …
```
=> Fix: tactical failed when the ship's all skills are leveled max

module/config/config_updater.py
`set`是无序的，这导致运行`config_updater.py`可能会无意义地更改`option_bold`，在commit中塞入大量垃圾内容。
=> Opt: sort latest events in config update

module/retire/enhancement.py
Fix [#3656](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3656#issuecomment-2068367061)
跑了一遍完整的强化
改名需谨慎，警钟敲烂
=> Fix: rename equipment functions

module/equipment/equipment_change.py
1. info_bar导致图像裁剪出错
2. 动画太慢导致装备还没加载完全
=> Fix: equipment image record in fast PC

config/template.maa.json, submodule/AlasMaaBridge/module/config/argument/args.json, submodule/AlasMaaBridge/module/config/argument/argument.yaml, submodule/AlasMaaBridge/module/config/argument/task.yaml, submodule/AlasMaaBridge/module/config/config_generated.py, submodule/AlasMaaBridge/module/config/config_updater.py, submodule/AlasMaaBridge/module/config/i18n/en-US.json, submodule/AlasMaaBridge/module/config/i18n/ja-JP.json, submodule/AlasMaaBridge/module/config/i18n/zh-CN.json, submodule/AlasMaaBridge/module/config/i18n/zh-TW.json, submodule/AlasMaaBridge/module/handler/handler.py
更正部分文本
新增以下功能：
- 基建换班 - 训练完成后继续尝试专精当前技能
- 收取信用及购物 - 只购买打折的信用商品 
- 收取信用及购物 - 300以下信用点停止买商品
- 领取日常奖励 - 领取所有邮件奖励
- 领取日常奖励 - 进行限定池赠送的每日免费单抽
- 领取日常奖励 - 领取幸运墙的每日合成玉奖励
- 领取日常奖励 - 领取五周年赠送月卡奖励
=> Upd: Support MAA v5.2.3-alpha.1.d011.g704145a3d

module/os_handler/map_event.py
避免在fast PC上出现这样的点击
```Text
─────────────────────────────────────────────────── OS AUTO SEARCH ────────────────────────────────────────────────────
2024-05-23 00:12:29.565 | INFO | OS AUTO SEARCH                                                                        
2024-05-23 00:12:29.577 | INFO | Click (1232,  540) @ AUTO_SEARCH_OS_MAP_OPTION_OFF                                    
2024-05-23 00:12:29.653 | INFO | Click (1237,  539) @ AUTO_SEARCH_OS_MAP_OPTION_OFF_DISABLED                           
2024-05-23 00:12:31.266 | INFO | OS auto search finished                                                               
2024-05-23 00:12:31.269 | INFO | Ash beacon status: light                                                              
2024-05-23 00:12:31.300 | INFO | [ASH_COLLECT_STATUS …
```
=> Fix: avoid continuous clicking AUTO_SEARCH_OS_MAP_OPTION_OFF

module/gacha/ui.py, module/ui/navbar.py
Navbar应当不存在`active is None`的状态，这个判断在 d51fc8f 被去掉，但看起来只是一个临时更改
#3822 去掉目前多余的`Navbar.set`
=> Opt: wait until navbar active is not None

module/tactical/tactical_class.py
修复tactical功能日志输出时错误的对datetime对象进行迭代的问题
=> fix exception when tactical book is empty

module/minigame/minigame.py
close #4130 
原来的设计会导致本月tickets达到上限的弹窗被关掉，从而回到游戏大厅，这不符合处理弹窗的目的；再加上游戏大厅里面检测MINIGAME_SCROLL.appear不安全，所以进行此更改
=> Fix: wrong popup dealing in minigame

module/os/operation_siren.py
短猫遇到#3747 的情况时，若设置了指定海域，可能会重复遇到而触发RequestHumanTakeover
[log.txt](https://github.com/user-attachments/files/16735557/log.txt)
=> Fix: refresh current zone first if OpsiMeoTargetZone!=0

module/device/method/ldopengl.py
可能由于雷电提供的dll中存在一定的异步行为，alas对截图的处理如果跟截图行为共用内存，有概率因为存取冲突导致截图异常
获取截图后拷贝内存可以解决这一问题，但存在一定的性能损失
先把PR开着，测试24小时没问题之后再合
=> Fix: ldopengl screenshot reverse color

campaign/campaign_main/campaign_15_base.py
修一下15图的filter。之前一直抄的14图的filter，发现没验证航空型敌人导致出现问题，修改后能验证航母类敌人。
具体排序可能还得讨论一下（如有必要）
=> Fix: wrong campaing_main_15 enemy filter

submodule/AlasMaaBridge/module/handler/handler.py
maa剿灭作战的任务回调会固定返回重复代理的错误，临时跳过这个错误使剿灭可用
=> Fix: Skip maa annihilation error task callback temporary

module/campaign/run.py
对于 #4214 
启用任务平衡时`handle_task_balancer`直接停止任务，在主线任务运行时游戏处于如下页面
此时判断到了 `AUTO_SEARCH_MENU_CONTINUE`,
进入 `module/campaign/run.py:370` `ensure_auto_search_exit`内，
由于新活动`TEMPLATE_STAGE_CLEAR`不通用，在新活动图界面主线图的`campaign_extract_name_image`只会返回`[]`, `ensure_auto_search_exit`会陷入死循环
若是正常结束活动图，则正常执行 `ensure_campaign_ui`切换到 `page_campaign`
触发方式有3种，只有在使用`TEMPLATE_STAGE_CLEAR_20240725`的活动中才能触发:
1. 启用任务平衡，在一次活动图结束后由`handle_task_balancer`切换到任务`Main`;
2. 在活动图结算页面直接启动主线图
3. 在主线图结算页面直接启动活动图
一开始是想在`handle_task_balancer`中`task_stop()`前加一句`self.ui_goto_campaign()`，但是可能会有人触发方式2或3导致报错，`ensure_campaign_ui`里`ui_additional`已包含点击`AUTO_SEARCH_MENU_EXIT`退出结算页面，所以将370行`ensure_auto_search_exit`删除，测试了一遍上面三种情况均不会触发了，就是不知道这里的`ensure_auto_search_exit`有没有什么特殊应对情况。
=> Upd: In some events, ensure_auto_search_exit enters a dead loop

module/retire/enhancement.py
关联：#4023 
主要参照原代码逻辑，对强化失败后的产生的重复无效行为进行剔除，增加失败时的"state_enhance_attempt" → "state_enhance_confirm" →"state_enhance_fail"状态链判定，在符合该状态链中，连续剔除`['ENHANCE_RECOMMEND', 'SHIP_SWIPE', 'ENHANCE_CONFIRM']`三个状态。
修改后尝试了本次活动，目前可以正常强化超过2个战斗中的船只。
=> 尝试修复强化战斗中船只导致的too_many_click异常

campaign/event_20241024_cn/t4.py
现有的`image > 221`无法识别T4中的精英怪，下降到181后可以正常识别。
=> tmp: predict_enemy_genre in event_20241024_cn

submodule/AlasMaaBridge/module/asst/asst.py
Fixes #4314 
在加载MAA前，使用来自System32的依赖覆盖掉Python自带的依赖，以解决依赖版本错误的问题
=> Fix: Compatible with new versions of maa

gui.py, module/submodule/submodule.py, module/webui/app.py, module/webui/fake_pil_module.py, module/webui/process_manager.py, submodule/AlasMaaBridge/maa.py, submodule/AlasMaaBridge/module/asst/asst.py, submodule/AlasMaaBridge/module/handler/handler.py
#4314
在经历了漫长的试错之后，总算对这个问题有了正确的认识，整个问题分为两部分，
1.正常情况下，PIL库加载的时候会加载自己的msvcp140.dll，pywebio库依赖于PIL库的typehint，但是没有实际使用PIL库中的内容，multiprocessing.Process在启动子进程的时候会根据调用文件加载环境，意外加载了PIL库，导致MAA的dll加载时出现依赖版本冲突
2.Pycharm调试的情况下，multiprocessing.Process在启动子进程的时候会加载Python内置的msvcp140.dll，也会导致MAA的dll加载时出现依赖版本冲突
这个pr解决了正常情况下的依赖版本冲突问题：
在主进程启动的时候填充假的PIL库，避免主进程加载不必要的PIL库，也避免了子进程在启动的时候加载PIL库
在子进程启动完成后删除继承到的假的PIL库，Alas实例可以在需要的情况下重新加载真实的PIL库
在MAA实例启动后，加载PIL库之前，抢先加载正确版本的运行库
为了避免可能存在的不同版本运行库混用的问题，我根据MAA的dll依赖，加载了全套的运行库
但是由于vcruntime140.dll跟Python绑定非常深，无法通过直接替换文件以外的方式解决，所以还是没法完全避免混用
混用不一定会导致问题，需要一段时间的测试，保证MAA调用到的所有运行库成员在当前dll里面有就行
调试状态下的问题因为比较底层，所以没法给出项目内的解决方案，如果想要使用调试，可以通过在Python根目录\Lib\site-packages下建立sitecustomize.py文件，然后编辑为类似
import os
import ctypes
ctypes.WinDLL(os.path.join(os.environ['SystemRoot'], …
=> Add: fake module PIL for webui

module/exercise/combat.py
演习中途会遇到误识别BATTLE_STATUS_D的情况，原因有待排查，但这个bug存在会导致抓瞎，极大影响演习撤退的功能，因此提出此临时修改。
修改前：
修改后：
=> Tmp: resume low hp detection after false BATTLE_STATUS

campaign/campaign_main/campaign_2_1.py, campaign/campaign_main/campaign_2_2.py, campaign/campaign_main/campaign_2_3.py, campaign/campaign_main/campaign_2_4.py, campaign/campaign_main/campaign_2_base.py, campaign/campaign_main/campaign_3_1.py, campaign/campaign_main/campaign_3_2.py, campaign/campaign_main/campaign_3_3.py, campaign/campaign_main/campaign_3_4.py, campaign/campaign_main/campaign_3_base.py, module/exercise/hp_daemon.py, module/hard/hard.py
Apparently clicking the exercise button was only the effect but not the cause, since exp_info_B also appears in 2-4 logs. The ultimate reason was the B in the exp info can **perfectly** integrate into the chapter background, like this:
Commit c9fff1efa29f9e62cdf44d158f343748b2841a28 addressed this issue by moving out from the exercise page, but it just goes back in again so the program still crashes.
This commit should solve this issue for chapters 2 and 3. I did not make this solution up; instead this interesting heirarchical trick was already included in the 20221222 event. This should resolve issues #4553 #4425 #4434 .
Why this does not harm a genuine B status: because the page_campaign asset does not appear in a genuine exp info page.
BTW my branch was sync with main so I have Saar's …
=> Bugfix: clicking exercise button after stage 3-4

module/shop/shop_voucher.py
The issue was due to a line of incorrect logic: the scroll was moved to the bottom instead of to the next page. This edit should resolve it.
I have also checked if there are similar usages of set_bottom for hardwired logic, but I found none, so only this change.
By merging this pr, issues #4550 and #4532 should be closed.
=> Bugfix: Opsi Voucher Shop unable to buy coins and books

module/os/operation_siren.py
侵蚀一应该也是消耗ap的任务，不应该跟开荒抢ap？
如果不做请直接关闭
=> Opt: delay cl1 before os_explore finishes

submodule/AlasFpyBridge/fpy.py, submodule/AlasFpyBridge/module/FGOpy.py, submodule/AlasFpyBridge/module/config/argument/args.json, submodule/AlasFpyBridge/module/config/argument/argument.yaml, submodule/AlasFpyBridge/module/config/i18n/en-US.json, submodule/AlasFpyBridge/module/config/i18n/ja-JP.json, submodule/AlasFpyBridge/module/config/i18n/zh-CN.json, submodule/AlasFpyBridge/module/utils/headlessCliApplication.py
今天梦中惊醒,忽然想起去年7月15日我向FGO-py中引入[PEP 540](https://peps.python.org/pep-0540)导致的AlasFpyBridge完全无法使用的问题仍然没有得到修复!这是非常糟糕的!所以我向相关源码中添加了18个字节以修复此问题!
简单来说,PEP540会将python默认的编码从locale()改成utf-8,以前需要手动写encoding='utf-8'的地方都不用写了(正好我经常忘记写),在PIPE中输出时的字节流也是utf-8的,这使得在阿拉善这边需要指定编码,*我们先进的磁能坦克已经完全超越了老旧的天启坦克*
与此同时,也修复了(自2023年6月起就存在但是由于一个在FGO-py本体中做了walkaround另一个可以不经过ui直接改配置文件的原因显得一点都不紧急而躺在我的硬盘中许久但迟迟没有推送的) 1.特殊掉落计数更新时访问不存在的成员 与 2.时间间隔正则表达式 的两个错误
关于我2023年5月(或更早?)就承诺过的*在Alas中完成FGO的每周任务,使得用户的干预从每周一次降低到每个服务器维护一次*的美好愿景将在我回到日本拥有良好的网络连接后进行开发
=> Fix: [FPY] 我要保证我见到lme的时候AlasFpyBridge是可用的!

module/campaign/gems_farming.py, module/retire/scanner.py
激进地换前排并不会导致船坞溢出，还能减少因为前排没心情造成的换船次数。
加上目前换不换船都得先拆装备，不存在时间差距，所以应当激进地替换前排为当前心情值最高的可用前排。
=> Fix: vanguard_change logic

module/os/map_operation.py
这个rgb的调参是按以前有问题的图片在threshold=127情况下全部正确的rgb算聚类算出来的。至于为什么这种黑边灰中心的字体能通过测试我也不理解。
目前经过短猫3海域绕两圈的测试，没发现问题。
一些图片的处理效果：
=> Upd: ocr params for get_zone_name in JP server

README_en.md
- Extend the EN README with the "Correctly Using the Scheduler" and "Modify Game Settings" sections for alignment with the CN README.
- Correct typo: "manul" -> "manual"
=> Upd: [EN] Add missing scheduler and setting sections
