- module/config/argparser_en.py
Current batch has:
```
@echo off
Py alas_en.pyw
```
To make it work:
```
@echo on
call [activate your venv here]
call python alas_en.pyw
```
if gooey is not installed then an error would show up, reason why to use venv
> Fix: Batch GUI start

- campaign/campaign_main/campaign_9_4.py
> add 9-4 map 

- config/template.ini
- doc/future_plan.md
- module/campaign/campaign_ui.py
- module/campaign/run.py
- module/config/argparser_en.py
- module/config/config.py
- module/config/dictionary.py
- module/reward/commission.py
- Now is possible cleared a hard map like a normal map, Need add support to CN version in dic_chi_to_eng
Fix: [EN] Fix Miss detect lines as characters in Commission module, Thanks @LmeSzinc for help again.
> Add: Added support for hard map

- module/config/argparser_en.py
- module/exercise/opponent.py
Let me know if I should also update the arg_parser for CN and JP as well. Otherwise, this is only in EN, I made it so that max_exp is the default value for the variable "method" in get_priority just as the help info says.
I can also update that information for EN as well so user's know about the mode as well.
Thanks
> Add exercise mode "easiest"

- Easy_Install-V2.bat
- dev_tools.bat
> Added disclaimer to Easy_Install-V2

- Easy_Install-V2.bat
- alas.bat
- dev_tools.bat
- module/config/argparser.py
- module/config/argparser_en.py
- module/config/argparser_jp.py
- module/logger.py
- module/update.py
- added CN and JP version too
Tweak: A lot of tweaks in alas.bat and Easy_Install-V2.bat
- Now will check each dependency and if return error will warning where is the problem
- Added logging
> Fix: fix UTF-8 encode on non-UTF-8 systems

- alas.bat
- dev_tools.bat
- doc/How_to_update.md
- module/device/connection.py
Renamed folder python-3.7.6.amd64 to toolkit
> Fix: changed the path to match with alas.bat

- alas.bat
Fix: change the method to Gitee users 
- Now Gitee users can choose which repository want to use.
> Fix: fix mistype

- alas.bat
- dev_tools.bat
Dev_tools: Change the method to get datetime
- Now we use WMIC to get datetime to avoid issues due different time locales
> Enhancement: Now in first run when you enter your HOST:PORT the value will be replaced in alas.ini

- campaign/campaign_main/campaign_11_4.py
posible fix for crashes when boss spawns on bottom right:
"IndexError: index 0 is out of bounds for axis 0 with size 0"
> fix for 11-4

- campaign/event_20200716_en/a1.py
- campaign/event_20200716_en/a2.py
- campaign/event_20200716_en/a4.py
- campaign/event_20200716_en/c1.py
- campaign/event_20200716_en/c3.py
- campaign/event_20200716_en/c4.py
- campaign/event_20200716_en/d1.py
- campaign/event_20200716_en/d2.py
- module/daily/daily.py
- module/map/map.py
- module/reward/commission.py
Fix: [EN] Minor fix in commission dictionary
> Fix: Fixed stuck at grand capture map

- README.md
- campaign/campaign_main/campaign_11_4.py
- campaign/campaign_main/campaign_12_4.py
- module/logger.py
Docs: added wiki link on readme
> Opt: optmize 11-4 and 12-4 

- module/config/argparser.py
- module/config/argparser_en.py
- module/config/argparser_jp.py
- module/equipment/equipment.py
- module/retire/enhancement.py
Fix: Fewer tries on swipe to shorten duration and use ensure_no_info_bar to acquire new screenshot without info_bar
Added: Implementation of _enhance_choose_simple, simplified version of _enhance_choose, specifically enabled only if enhance_order_string is populated
Updated: help info for enhance_order_string with example input, removed subtext header info.
> Enhancement Updates

- README.md
- alas.bat
- module/hard/hard.py
- removed mandatory run alas.bat as administrator, now is optional
> Fix: fix alas.bat closing when menu input is null

- module/equipment/equipment.py
- module/retire/enhancement.py
…t doesn't match any condition. If detected, will perform a force check/swipe if applicable. Applied similar concept to both versions of _enhance_choose*.
Update: Swipe process with additional internal delay and wait_until_stable to ensure image is screen captured at approriate time.
Update: Keep sidebar click index positive otherwise can click back button. Add PRY condition with sidebar only having 3 buttons, disable clicking the Research button as not supported. Maybe in the future.
> Fix: Enhance process able to get trapped in loop if current screenshot

- module/map/fleet.py
- module/map/map_operation.py
to ensure submarine_view is 'off' while calculating.
> Fix: handle_strategy() before perspective calculation

- module/reward/reward.py
> Fix: might be infinite loop if we couldn't start a new research

- module/combat/level.py
> Fix: pre_process of LevelOcr may return NoneType

- module/map_detection/grid_info.py
Prevent enemy_genre from being overwritten by 'Enemy'.
For example:
Here E1 that was 2L, is overwritten by 2E after the scan, for it is covered by the fleet in E3 after battle. It is better to keep 2L because the genres of normal enemies do not change.
```
2020-11-23 10:47:53.736 | INFO |    A  B  C  D  E  F  G  H
2020-11-23 10:47:53.736 | INFO | 1 -- ++ -- -- 2L -- -- --
2020-11-23 10:47:53.737 | INFO | 2 MY ++ ++ -- -- -- 2L --
2020-11-23 10:47:53.737 | INFO | 3 Fl -- -- -- 2L -- -- --
2020-11-23 10:47:53.737 | INFO | 4 -- FL -- -- -- -- ++ ++
2020-11-23 10:47:53.737 | INFO | 5 -- -- -- 2L -- -- ++ ++
2020-11-23 10:47:53.740 | INFO |      A    B    C    D    E    F    G    H
2020-11-23 10:47:53.740 | INFO | 1    4 9999    6    5    6    7    8    9
2020-11-23 10:47:53.740 | INFO | 2 …
```
> Opt: grid.merge() optimization

- campaign/Readme.md
- module/config/event.py
Thank you LmeSzinc for making this handy dev tool!
> Add: EN The Enigma and the Shark Rerun event

- module/map/map_fleet_preparation.py
After the update of auto search, ALAS needs to clear and reselect fleets every time before entering a map. 45c50bda294fbbdd9342ebd7b393de3ce6879359
It is better to add some check to ensure that fleets are selected correctly, because emulators may drop clicks randomly.
> Opt: ensure fleets selected correctly in preparation

- module/guild/logistics.py
Current codes for CN server do not work for JP server and get stuck for normal members if no guild mission is found.
```
2021-02-22 00:35:33.660 | INFO | <<< GUILD LOGISTICS >>>
2021-02-22 00:35:33.675 | INFO | Guild supply button active
2021-02-22 00:35:33.675 | INFO | Click (1136,  636) @ GUILD_SUPPLY
2021-02-22 00:35:34.070 | INFO | Guild supply button active
2021-02-22 00:35:34.071 | INFO | Click (1171,  629) @ GUILD_SUPPLY
2021-02-22 00:35:34.441 | INFO | Guild supply button inactive
2021-02-22 00:35:34.442 | INFO | No guild mission found, mission of this week may not started
2021-02-22 00:35:34.442 | INFO | Guild mission choose found
2021-02-22 00:35:34.442 | INFO | Click (1111,  290) @ GUILD_MISSION
2021-02-22 00:35:34.809 | INFO | No guild mission found, mission of this week may …
```
> Fix: [JP] Guild mission choose disabled until we get the screenshot

- campaign/event_20210325_cn/c1.py
- campaign/event_20210325_cn/c2.py
- campaign/event_20210325_cn/c3.py
- campaign/event_20210325_cn/cs1.py
- campaign/event_20210325_cn/cs2.py
- campaign/event_20210325_cn/d1.py
- campaign/event_20210325_cn/d2.py
- campaign/event_20210325_cn/d3.py
- campaign/event_20210325_cn/ds1.py
- campaign/event_20210325_cn/ds2.py
Transcribed the configs used in AB to CD counterparts.
Ran up to C3 myself, error prone but can't do much about movable enemies or high frequency of map walk out of step. Would suggest for local changes until safe, comment out the `clear_siren()` to just allow clearing nearby enemies until boss.
> Add: Ashen Simulacrum chapter CD

- module/equipment/equipment.py
- enhance stuck due to asset altered via `wait_until_stable` / `load_color`, changed to `wait_until_appear`
> Fix: enhance stuck fix in equipment

- module/shipyard/ui.py
> Fix: return right BP count of target index

- module/retire/retirement.py
> Fix: [JP] retirement error 

- module/reward/reward.py
```
2021-08-23 09:35:43.271 | INFO | <<< MISSION REWARD >>>
2021-08-23 09:35:43.272 | INFO | [UI route] page_main - page_mission
2021-08-23 09:35:43.272 | INFO | <<< UI CLICK >>>
2021-08-23 09:35:43.276 | INFO | Click ( 877,  680) @ MAIN_GOTO_MISSION
2021-08-23 09:35:45.054 | INFO | REWARD_SIDE_NAVBAR set to left=1 upper=1
2021-08-23 09:35:46.096 | INFO | Click (1138,  138) @ MISSION_SINGLE
2021-08-23 09:35:48.031 | INFO | Click (1020,  673) @ GET_ITEMS_1
2021-08-23 09:35:51.113 | INFO | REWARD_SIDE_NAVBAR set to left=5 upper=5
2021-08-23 09:35:51.115 | INFO | Click (  50,  542) @ REWARD_SIDE_NAVBAR_0_4
2021-08-23 09:35:53.088 | INFO | Click (1062,   17) @ MISSION_MULTI
2021-08-23 09:35:53.996 | INFO | Click (1028,  656) @ GET_ITEMS_1
2021-08-23 09:35:55.116 | INFO | Click (1135,  130) @ …
```
> Fix: avoid to click unfinished weekly mission

- module/reward/meowfficer.py
MEOWFFICER_INFO  appears later than page_meowfficer. 
Sometimes it appears after `self.ui_ensure(page_meowfficer)`.
#592
> Fix: handle MEOWFFICER_INFO  appearance delay

- module/research/research.py
> Fix: [JP] avoid research projects positions bug

- module/reward/reward.py
- module/sos/sos.py
> Fix: avoid sos calls daily_sos again

- module/os_ash/ash.py
> Fix: handle ash beacon outdate in preparation page

- module/equipment/equipment_change.py
> [fix]: "list.remove(x): x not in list" error

- alas.py
- config/template.json
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/argument/menu.json
- module/config/argument/override.yaml
- module/config/argument/task.yaml
- module/config/config_generated.py
- module/config/config_manual.py
- module/config/config_updater.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/event/campaign_cd.py
还没测试哈，今天的图打完了，我明天测试一下。
不过基本都是抄的群主代码
> 添加了CD图配置，可以供以配置不同的fleet

- module/config/i18n/en-US.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/device/connection.py
Add: find_bluestacks5_hyperv method
Fix: Serial help document
> Add: Bluestacks5 Hyper-v method

- module/device/connection.py
> change: move import winreg from head to def

- module/combat/combat.py
> Fix: check expected end before combat status

- config/template.json
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/argument/task.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/tactical/tactical_class.py
Fixes:
- re-factor tactical exp progress check
- streamline book removal process
- if resort to 'first' not a Book type, so no button attribute
> Fix: Refactor RewardTacticalClass

- config/template.json
- gui.py
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/argument/menu.json
- module/config/argument/task.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/daemon/game_manager.py
目前仅实现了强制关闭，和可选的关闭后重启。
饼：
~~什么时候学会了Python和pywebio什么时候加上去（）~~
> Add Game Manager (WIP)

- module/research/project.py
去除多余的'-'，对资金募集项目手动加上'G'，Fix #836
> 台服科研项目识别的容错处理

- assets/gui/css/alas-mobile.css
- assets/gui/css/alas.css
- assets/gui/css/dark-alas.css
- assets/gui/css/light-alas.css
- module/daemon/benchmark.py
- module/logger.py
- module/webui/app.py
- module/webui/process_manager.py
- module/webui/setting.py
- module/webui/utils.py
- module/webui/widgets.py
- requirements-in.txt
- requirements.txt
> Opt: Rich logging

- module/research/research.py
> Fix: handle research remain 00:00:00 correctly

- module/device/app_control.py
- module/device/connection.py
- module/device/device.py
- module/device/method/wsa.py
加了方案的硬编码
serial填127.0.0.1:58526会警告
修复了打开游戏之后再打开app会导致运行状态检测错误的问题
> Fix: Improved the logic of getting package name on WSA

- .gitignore
- deploy/AidLux/0.92/requirements.txt
- module/config/utils.py
- requirements-in.txt
- requirements.txt
保存配置的行为现在是原子的，保存过程中退出会留下一个临时文件
> Fix: The behavior of saving the configuration will be atomic

- module/base/button.py
- module/device/method/utils.py
- [Fix: Handle AdbError: unknown host service](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/49a2ec651981ecfabafd486ebde95f83d8466026)
- [Fix: Button.image_binary is used before assignment](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/09577297c829d58787c3e87054e8378a7061d62d)
> Fix: Button.image_binary is used before assignment

- module/research/project.py
- module/research/research.py
这个pr经过了基础的测试
我发誓我再也不会不测试就改代码了
#1119 
修复了不能正常工作的严重错误
增加了对不含reset的过滤器的支持
> Fix: Added support for filters that lack reset

- config/template.json
- module/combat/combat.py
- module/commission/commission.py
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/config_generated.py
- module/config/config_updater.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/config/redirect_utils/utils.py
- module/handler/mystery.py
- module/map/map_operation.py
- module/meowfficer/buy.py
- module/meowfficer/collect.py
- module/os/fleet.py
- module/os/map.py
- module/research/research.py
- module/statistics/azurstats.py
这个pr经过了基本的测试，其中一对多部分因为缺少样例没有进行测试，但是代码很简单
更新了config_redirect的实现，使其能满足多对多的重定向需求
合并了保存截图和上传截图的选项
> Opt: Combined save and upload options

- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/research/preset.py
为科研策略增加预设选项
1. `三期 蓝图+234` 
2. `三期 仅蓝图` 
3. `三期 仅234` 
4. `二期兼顾三期 457+234` 
5. `二期 蓝图+457` 
6. `二期 仅蓝图`
> Add: more research preset

- module/device/connection.py
Using `QueryValueEx` to find the value of a registry subkey directly instead of for-if-eq-loop.
Besides, the behavior of `find_bluestacks5_hyperv` has been changed:
When there's no port found in `bluestacks.conf`, `RequestHumanTakeover` will be raised immediately, otherwise `find_bluestacks5_hyperv` would retry 3 times while `adb_connect` would retry 3*3=9 times totally, etc., and all of which are bound to fail.
> Opt: BlueStacks Hyper-V connection improvement

- deploy/config.py
- deploy/template
- gui.py
- module/webui/app.py
Fix: Require password when password is null
> Fix: Option to disable reloader

- module/webui/app.py
> Opt: Update Emotion Record if Emotion Value is changed

- module/research/preset.py
- module/research/project.py
- module/research/research.py
这个pr经过了初步的测试
小手一抖分支就炸了，想了下重开算了
#1160 
删掉了大部分过滤器里的T系列科研项目
优化了一下遇到低质量项目的行为，我严重怀疑原本的写法会出大问题
另外低质量项目的定义可能还要讨论（
> Opt: Enforce research when get a low-quality project Ver2

- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/research/preset.py
> Add: new research preset: S2 457 only

- deploy/docker/Dockerfile
> Init uiautomator2 to prevent minitouch init error

- deploy/alas.py
- deploy/config.py
- deploy/emulator.py
这是一个简单的pr且经过了基本的测试
用>nul 2>nul屏蔽了taskklill的输出，用返回值判断执行情况
清理alas和清理adb的代码不一样
前面那个考虑到已经输出了返回值，就不大改了
后面那个则是根据返回值print相关的提示
反正只要没有大大的中文的“错误”，就不会有群友天天问
> Opt: Optimized output when execute 'taskkill'

- module/config/i18n/en-US.json
Add few spaces to unify the format of task name
> Opt: Minor task name fix

- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/map/fleet.py
#1440 
Change the name more precisely
更精確的命名文本，但不知道有沒有缺漏
我用搜索U522只找到這些
edit:使用PyCharm的檔案檢索功能已完成所有取代，功能正常執行也未造成任何衝突
> Opt: Change"UseU522Skill" into "UseOpenOceanSupport"

- module/tactical/tactical_class.py
Upd: Update threshold value to match images with random flashes that appear on rainbow books.
> Solve 1353

- config/template.json
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/argument/task.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/device/connection.py
- module/device/device.py
- module/device/emulator.py
- module/device/screenshot.py
- module/exception.py
- module/handler/login.py
基本的功能都写的差不多了，可能还有点要塞的东西
已经完成的部分：
根据serial自动识别模拟器，重启模拟器（暂时仅限夜神MuMu蓝叠5）
通过自定义命令重启模拟器（任意模拟器）
还未完成的部分：
在考虑要不要做空闲时关闭模拟器
> Add: Emulator auto detect and restart

- config/template.json
- module/config/argument/args.json
- module/config/argument/argument.yaml
- module/config/config_generated.py
- module/config/i18n/en-US.json
- module/config/i18n/ja-JP.json
- module/config/i18n/zh-CN.json
- module/config/i18n/zh-TW.json
- module/device/emulator.py
- module/handler/login.py
按照lme的要求调整了重启模拟器的选项
尝试过修改夜神模拟器的启动参数，但是需要修改的地方会变得很多
> Upd: Modified some options for restart emulator

- module/device/emulator.py
> Fix: Unexpected None from detect_emulator(Fix #1580)

- alas.py
> Fix: Redundant restart when checker recovered (#1579)

- module/notify.py
修复了使用CustomProvider时丢失title与content的问题。
> Fix: Missing title and content in notify

- config/deploy.template-AidLux-cn.yaml
- config/deploy.template-AidLux.yaml
- config/deploy.template-cn.yaml
- config/deploy.template-docker-cn.yaml
- config/deploy.template-docker.yaml
- config/deploy.template.yaml
- deploy/config.py
- deploy/template
- module/webui/app.py
Auto-run specified config when startup
> Add: auto-run config in deploy

- deploy/emulator.py
- deploy/install/emulator_windows.py
- module/device/emulator.py
新的代码暂时还没空细看，随便搓了个能解决问题的代码，但是因为始终问不到出问题的模拟器所以无法实测
> Fix: UnicodeDecodeError when getting serial

- deploy/git.py
我总感觉git那边的报错跟这个是间接关系，总之我不好说，先把这个问题修了
> Fix: FileNotFoundError when removing git config

- module/webui/app.py
把所有危险行为放在了最前面的地方，不给上锁只能做到这种地步
建议这块代码需要870大师检查后再合并（或者lme感觉没问题也行）
> Fix: Config save to wrong file when switch config

- config/template.maa.json
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/override.yaml
修复了maa插件清理智功能无法使用的严重bug
过几天我会写用override.yaml修改现存配置的功能，还好前面的没合进master，现在想修复只能重建配置或手动修改配置文件
> Fix: Stop condition of MaaFight set incorrectly

- config/template.maa.json
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/argument.yaml
- submodule/AlasMaaBridge/module/config/argument/default.yaml
- submodule/AlasMaaBridge/module/config/argument/override.yaml
- submodule/AlasMaaBridge/module/config/config_generated.py
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/handler.py
> Add: force_shopping_if_credit_full of MAA

- campaign/Readme.md
- module/config/argument/args.json
- module/config/i18n/zh-TW.json
修复了Readme里文件夹配置错误导致config_updater会搞乱一切的bug
还是我又搞错了什么？
可能包含了#1851，但是我没测试过
lme审pr的时候一定要运行一次config_updater，前两天我刚擦完一次屁股
> Fix: Wrong campaign folder in Readme.md

- campaign/campaign_main/campaign_7_4.py
reduce the weight of A2, A2, [C3,D2], G4
delate some roadblocks
> Opt: Update pathfinding weight_data & roadblocks

- module/handler/strategy.py
不小心打錯還把原本的改了，感謝[VirtualTowel](https://github.com/VirtualTowel)提醒我收自己的爛攤子
> Fix: Wrong statement in submarine hunt

- module/retire/scanner.py
> Fix: Threshold adjust for TEMPLATE_FLEET_4

- module/os_handler/strategic.py
提升了启动计划作战部分的代码健壮性以解决识别失效导致运行混乱的问题
可能需要lme帮忙检查STRATEGIC_SEARCH_POPUP_CHECK是否完全有效
> Opt: Improve robustness of strategic search

- deploy/config.py
- module/webui/app.py
修复了无法基于mod配置新建配置的问题
删除了没有任何价值的error_code
> Fix: Unable to create new config from existing mod config

- module/os_handler/strategic.py
注意到以AUTO_SEARCH_OS_MAP_OPTION_OFF作为结束条件不是在所有设备上可信，因此放宽了条件
> Opt: Adjusted logic of strategic search

- campaign/war_archives_20190321_en/a1.py
- campaign/war_archives_20190321_en/a3.py
- campaign/war_archives_20190321_en/c1.py
- campaign/war_archives_20190321_en/c3.py
A1 A3 C1 C3都有舰队出生在左上角的情况，所以一起修改了
不怎么会用github 见笑了
> bug_fix:修复了作战档案红染的参访者进图找不到舰队的问题

- config/template.maa.json
- submodule/AlasMaaBridge/maa.py
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/menu.json
- submodule/AlasMaaBridge/module/config/argument/task.yaml
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/asst_backup.py
- submodule/AlasMaaBridge/module/handler/handler.py
更新了使用的接口以应对v4.8.0的文件名变化
移除了MAA在v4.8.0合并的访问好友任务
> Upd: Support of MAA v4.8.0

- config/template.maa.json
- submodule/AlasMaaBridge/maa.py
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/argument.yaml
- submodule/AlasMaaBridge/module/config/config_generated.py
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/asst_backup.py
- submodule/AlasMaaBridge/module/handler/handler.py
更新了触控方案和暂停下干员的选项
更新了使用的接口
完全抛弃了原生的接口（反正OTA更新不了）
> Add: Support of touch method for MAA

- submodule/AlasMaaBridge/maa.py
- submodule/AlasMaaBridge/module/handler/handler.py
修复了在MAA出现严重错误时不会停止调度器的错误
修复了一个文本错误
> Fix: Unable to stop MAA when error occurred

- module/device/method/adb.py
增加了使用adb shell am start启动app的功能
解决了mumu x上用adb控制时无法启动碧蓝航线的问题
> Add: Start app by adb shell am start

- deploy/adb.py
- module/device/connection.py
修复了因为MuMu X没有abi导致安装minitouch时链接错误的问题
> Fix: Unable to install minitouch in MuMu X

- submodule/AlasMaaBridge/module/handler/handler.py
MaaAssistantArknights/MaaAssistantArknights#3370
需要等待MAA正式版更新后合并
> Fix: Typo error in MAA interface

- module/config/i18n/en-US.json
- module/raid/daily.py
- Trivial forgot to return back to page_raid after acquiring the tickets from reward
- Trivial update to help text for RaidDaily for EN
> Fix: Raid EX support

- module/shop/base.py
勋章商店购买紫布里5个以上时会卡住，如图
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10552832/log.txt)
> Fix: medal shop get stuck when buy bulin  >5

- config/template.maa.json
- submodule/AlasMaaBridge/maa.py
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/menu.json
- submodule/AlasMaaBridge/module/config/argument/task.yaml
- submodule/AlasMaaBridge/module/config/config.py
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/handler.py
加入了生息演算功能
但是因为MAA的设计问题，一旦启用之后就会无限运行，会阻塞掉其他所有功能
正在找MAA那边商谈能不能加一点停止条件
> Add: Maa Reclamation Algorithm

- module/config/argument/args.json
> Fix: wrong args.json after merging

- config/template.maa.json
- submodule/AlasMaaBridge/module/asst/__init__.py
- submodule/AlasMaaBridge/module/asst/asst.py
- submodule/AlasMaaBridge/module/asst/updater.py
- submodule/AlasMaaBridge/module/asst/utils.py
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/argument.yaml
- submodule/AlasMaaBridge/module/config/argument/override.yaml
- submodule/AlasMaaBridge/module/config/config_generated.py
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/handler.py
更新了使用的MAA接口
增加了使用48小时内过期的理智药的功能
增加了肉鸽开局借助战的功能
> Upd: Support of MAA v4.11.0

- module/os_handler/action_point.py
> Fix: Handle 2 Infobars covering action_point ocr (#2278)

- deploy/docker/Dockerfile
- deploy/docker/Dockerfile.cn
- deploy/patch.py
Fix git ERROR: detected dubious ownership in repository at '/app/AzurLaneAutoScript'
> Fix: preventing updates in Docker

- config/template.json
- module/config/argument/args.json
- module/config/argument/override.yaml
> Opt: Only Delay 12 hours for Hazard1leveling

- submodule/AlasFpyBridge/module/config/argument/menu.json
- submodule/AlasFpyBridge/module/config/argument/task.yaml
- submodule/AlasFpyBridge/module/config/i18n/en-US.json
- submodule/AlasFpyBridge/module/config/i18n/ja-JP.json
- submodule/AlasFpyBridge/module/config/i18n/zh-CN.json
- submodule/AlasFpyBridge/module/config/i18n/zh-TW.json
我说我测试的时候都好好的怎么就不对了呢
一看，最后一个更改没add就commit了
> Fix: [FPY] `Start` button on tool page

- module/os/operation_siren.py
> Add: call cl1 if enabled after meowfficerfarming finished.

- campaign/campaign_main/campaign_2_4.py
Potential fix of #1979 and #2583.
However notice that there is still possibility that F2 and F1 both spawns at the final round.
> Add: Clear (potential) roadblocks first in 2-4

- module/os_combat/combat.py
对 #3101 的一个修复，也许可以同时处理 #2982 #2942 。
> Fix: End condition order in auto_search_combat of os_combat

- module/statistics/azurstats.py
> add: Migrate to a new image hosting service.

- module/os_handler/shop.py
> Fix[TW]: Akashi shop buttom grid

- module/raid/raid.py
使用 @hgjazhgj 提供的方法修复`CN`服共斗活动`寰昌宇定家事忙(raid_20240130)`中 pt ocr 识别错误的问题
> Upd: Update pt OCR recognition of raid_20240130

- campaign/Readme.md
- module/config/argument/args.json
- module/config/i18n/zh-TW.json
> Upd:[TW]Event:Winter Pathfinder

- campaign/Readme.md
- module/config/argument/args.json
- module/config/i18n/zh-TW.json
> Upd:[TW]Event:Revelations of Dust

- module/campaign/gems_farming.py
> Fix: Reset dock sorting after changing ship

- module/handler/auto_search.py
- module/map/map_fleet_preparation.py
应该是 #3577 的一种不依赖设置的处理方法。
https://github.com/LmeSzinc/AzurLaneAutoScript/assets/50830808/0459cd5a-e599-455b-9a35-acc4a680e886
> Opt: load offsets of auto search settings at fleet preparation stage

- campaign/war_archives_20191031_en/b2.py
- campaign/war_archives_20191031_en/b4.py
- campaign/war_archives_20191031_en/d2.py
- campaign/war_archives_20191031_en/d4.py
> Add: HOMO_STORAGE data for d2/d4 in Divergent Chessboard

- module/campaign/gems_farming.py
Fix #3638 
为什么不带克莱文、麦考尔、奥利克玩，是不喜欢吗.jpg
> Fix: fall back to all union DDs when not specifying DD

- campaign/campaign_main/campaign_15_3.py
- campaign/campaign_main/campaign_15_4.py
Fix #3563 where battle function is not chosen as intended when clear all fleets.
@Zuosizhu
> Fix: force battle function choice for 15-3/15-4 when clear all

- campaign/campaign_main/campaign_15_4.py
[15-4 dev(a4f8bde69) 开荒测试 右下小船堵路,打左上大航失败.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15073195/15-4.dev.a4f8bde69.zip)
> Opt: mob move strategy in 15-4

- campaign/Readme.md
- module/config/argument/args.json
- module/config/i18n/zh-TW.json
> Upd:[TW]Event:The Fool's Scales

- campaign/event_20240425_cn/campaign_base.py
> Fix: OCR error on letter muse (fixed #3719)

- module/equipment/equipment.py
- module/equipment/equipment_change.py
> Fix: check EQUIPMENT_OPEN using template matching

- config/template.maa.json
- submodule/AlasMaaBridge/module/config/argument/args.json
- submodule/AlasMaaBridge/module/config/argument/argument.yaml
- submodule/AlasMaaBridge/module/config/config_generated.py
- submodule/AlasMaaBridge/module/config/i18n/en-US.json
- submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
- submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
- submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
- submodule/AlasMaaBridge/module/handler/handler.py
新增 战斗 - 连战次数
新增 公招 - 三星 Tag 时的 Tag 倾向
新增 公招 - 公招多选 Tag 的策略
新增 掉落记录 - 上传到一图流
> Upd: MAA Fight&Recruit

- module/shipyard/shipyard_reward.py
> Fix: RewardShipyard ocr coin in page_reshmenu

- campaign/Readme.md
- module/config/argument/args.json
- module/config/i18n/zh-TW.json
> Upd:[TW]Event:Sundered Blue Rerun

- module/shipyard/shipyard_reward.py
> Fix: use ui_ensure to handle FATE(Unknown ui page)

- module/combat/combat.py
> Fix: handle combat mis click

- campaign/event_20220428_cn/a2.py
- campaign/event_20220428_cn/c2.py
> Fix: update camera_data of a/c2 in event_20220428_cn

- deploy/docker/requirements.txt
- deploy/docker/requirements_generator.py
- deploy/headless/requirements.txt
- deploy/headless/requirements_generator.py
> fix: add mxnet-alas for linux

- module/os_shop/item.py
- module/os_shop/port_shop.py
- module/os_shop/shop.py
- amount handler
- counter ocr should return number
- counter area
> fix: opsi amount handler and counter ocr

- campaign/event_20220526_cn/campaign_base.py
> Fix: predict_enemy_genre in event_20220526_cn rerun

- campaign/campaign_main/campaign_15_base.py
> Fix: Sync MOB_MOVE_OFFSET to campaign_15_base.py

- module/device/method/ldopengl.py
> Fix: ldopengl screenshot reverse color (#4136)

- module/config/argument/args.json
I think other dude just forgot
> Should allow EN/JP to use ALAS for new event

- .gitignore
另外请问，既然主仓库为保护 master 而在 dev 中开发，可否将 dev 设为 default branch？
> Upd: add Visual Studio to gitignore

- module/campaign/campaign_event.py
- module/war_archives/war_archives.py
> Fix: ensure not at war archives campaign in ui_goto_event

- module/meta_reward/meta_reward.py
> Fix: dossier reward receive

- module/commission/project.py
> Upd: [JP] commission suffix ocr pre_process

- module/os_handler/os_status.py
> upd: [JP] yellow_coin color

- module/commission/project.py
> Fix: jp commission suffix pre_process

- module/campaign/gems_farming.py
> Fix: z20_or_z21 should be filtered by any ship

- module/daily/daily.py
> Revert "tmp: [JP] OCR_REMAIN in daily"

- module/daily/daily.py
根据#4531 给的图调整了颜色，看来#4521 从(201, 201, 201)改成(255, 255, 255)也不太对。
> upd: [JP] OCR_REMAIN in daily

- module/os_shop/port_shop.py
- module/os_shop/ui.py
Fixed incorrect truncation of slider bar caused by high brightness of click effects.
fixes #3980 , #4417
> Fix: Incorrect truncation of slider bar

- deploy/docker/Dockerfile
- deploy/docker/Dockerfile.cn
> Fix: Installations in containers have no access to remote access

- module/freebies/mail_white.py
- module/ui/page.py
> Opt: allow entering page_mail from page_main

- module/os_combat/combat.py
> Opt: disable handle_get_items in OSCombat.combat_status
